sudo: required

language: python
python:
    - "2.7"

services:
  - docker

before_install:
    - docker pull rootproject/root-ubuntu16:snapshot

script:
    - docker run --rm  --privileged=true -v $TRAVIS_BUILD_DIR:/home/builder/Xbb -it rootproject/root-ubuntu16:snapshot /bin/bash -c "source /usr/local/bin/thisroot.sh;cd;cd Xbb/python/test;python ./run_all.py"
