tr -d '\r' < cuts.ini                    > cuts.ini
tr -d '\r' < datacards.ini               > datacards.ini
tr -d '\r' < lhe_weights.ini             > lhe_weights.ini
tr -d '\r' < plots.ini                   > plots.ini
tr -d '\r' < regression.ini              > regression.ini
tr -d '\r' < training.ini                > training.ini
tr -d '\r' < vhbbPlotDef.ini             > vhbbPlotDef.ini
tr -d '\r' < samples_nosplit.ini         > samples_nosplit.ini
tr -d '\r' < paths.ini.bkp               > paths.ini.bkp
tr -d '\r' < volatile.ini                > volatile.ini
tr -d '\r' < paths.ini                   > paths.ini
tr -d '\r' < general.ini                 > general.ini
