#!/bin/bash

REBINMETHOD="flats(5,15)"

echo "bin boundaries for method ${REBINMETHOD}"
echo ""
echo "dc:VV_SR_med_Znn_0j.rebin_list="`./submit.py -J runplot -T Zvv2017 -F tmp --regions VV_SR_med_Znn_0j --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_med_Znn_ge1j.rebin_list="`./submit.py -J runplot -T Zvv2017 -F tmp --regions VV_SR_med_Znn_ge1j --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high1_Znn.rebin_list="`./submit.py -J runplot -T Zvv2017 -F tmp --regions VV_SR_high1_Znn --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high1_Znn_BOOST.rebin_list="`./submit.py -J runplot -T Zvv2017 -F tmp --regions VV_SR_high1_Znn_BOOST --vars BDT_VZ_Zvv_BOOSTFinal_wdB --set="plotDef:BDT_VZ_Zvv_BOOSTFinal_wdB.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high2_Znn.rebin_list="`./submit.py -J runplot -T Zvv2017 -F tmp --regions VV_SR_high2_Znn --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high2_Znn_BOOST.rebin_list="`./submit.py -J runplot -T Zvv2017 -F tmp --regions VV_SR_high2_Znn_BOOST --vars BDT_VZ_Zvv_BOOSTFinal_wdB --set="plotDef:BDT_VZ_Zvv_BOOSTFinal_wdB.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`

exit

echo "dc:VV_SR_med_Wmn.rebin_list="`./submit.py -J runplot -T Wlv2017 -F tmp --regions VV_SR_med_Wmn --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_med_Wen.rebin_list="`./submit.py -J runplot -T Wlv2017 -F tmp --regions VV_SR_med_Wen --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high1_Wmn.rebin_list="`./submit.py -J runplot -T Wlv2017 -F tmp --regions VV_SR_high1_Wmn --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high1_Wen.rebin_list="`./submit.py -J runplot -T Wlv2017 -F tmp --regions VV_SR_high1_Wen --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high1_Wmn_BOOST.rebin_list="`./submit.py -J runplot -T Wlv2017 -F tmp --regions VV_SR_high1_Wmn_BOOST --vars BDT_VZ_Wlv_BOOSTFinal_wdB --set="plotDef:BDT_VZ_Wlv_BOOSTFinal_wdB.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high1_Wen_BOOST.rebin_list="`./submit.py -J runplot -T Wlv2017 -F tmp --regions VV_SR_high1_Wen_BOOST --vars BDT_VZ_Wlv_BOOSTFinal_wdB --set="plotDef:BDT_VZ_Wlv_BOOSTFinal_wdB.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high2_Wmn.rebin_list="`./submit.py -J runplot -T Wlv2017 -F tmp --regions VV_SR_high2_Wmn --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high2_Wen.rebin_list="`./submit.py -J runplot -T Wlv2017 -F tmp --regions VV_SR_high2_Wen --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high2_Wmn_BOOST.rebin_list="`./submit.py -J runplot -T Wlv2017 -F tmp --regions VV_SR_high2_Wmn_BOOST --vars BDT_VZ_Wlv_BOOSTFinal_wdB --set="plotDef:BDT_VZ_Wlv_BOOSTFinal_wdB.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high2_Wen_BOOST.rebin_list="`./submit.py -J runplot -T Wlv2017 -F tmp --regions VV_SR_high2_Wen_BOOST --vars BDT_VZ_Wlv_BOOSTFinal_wdB --set="plotDef:BDT_VZ_Wlv_BOOSTFinal_wdB.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`

echo "dc:VV_SR_low_Zmm.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_low_Zmm --vars VVDNNlow --set="plotDef:VVDNNlow.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_low_Zee.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_low_Zee --vars VVDNNlow --set="plotDef:VVDNNlow.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_med_Zmm_0j.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_med_Zmm_0j --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_med_Zee_0j.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_med_Zee_0j --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_med_Zmm_ge1j.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_med_Zmm_ge1j --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_med_Zee_ge1j.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_med_Zee_ge1j --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high1_Zmm.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_high1_Zmm --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high1_Zee.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_high1_Zee --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high1_Zmm_BOOST.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_high1_Zmm_BOOST --vars BDT_VZ_Zll_BOOSTFinal_wdB --set="plotDef:BDT_VZ_Zll_BOOSTFinal_wdB.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high1_Zee_BOOST.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_high1_Zee_BOOST --vars BDT_VZ_Zll_BOOSTFinal_wdB --set="plotDef:BDT_VZ_Zll_BOOSTFinal_wdB.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high2_Zmm.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_high2_Zmm --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high2_Zee.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_high2_Zee --vars VVDNN --set="plotDef:VVDNN.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high2_Zmm_BOOST.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_high2_Zmm_BOOST --vars BDT_VZ_Zll_BOOSTFinal_wdB --set="plotDef:BDT_VZ_Zll_BOOSTFinal_wdB.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
echo "dc:VV_SR_high2_Zee_BOOST.rebin_list="`./submit.py -J runplot -T Zll2017 -F tmp --regions VV_SR_high2_Zee_BOOST --vars BDT_VZ_Zll_BOOSTFinal_wdB --set="plotDef:BDT_VZ_Zll_BOOSTFinal_wdB.rebinMethod=${REBINMETHOD};Plot_general.redefineSignals=<!.|VVSIG!>" --local 2>1 | grep -A1 "new bin boundaries" | tail -n1 | sed 's/INFO:  //g'`
